In [185]:
import numpy as np
import pandas as pd

cat_df = pd.read_csv("cat_breeds_dirty.csv", sep=";")
cat_df.head()

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude
0,Angora,0.25,3.0,female,False,19.0,2.0,white,solid,blue,FALSE,wet,46.0,16.0,France,43.296482,5.369780
1,Angora,0.33,4.0,male,False,19.0,2.5,white,solid,blue,FALSE,wet,48.0,16.0,France,43.611660,3.877710
2,Angora,0.50,NaN,NaN,False,20.0,2.8,what does it mean dominant?,solid,green,I never allow my kitty outside!!!!!,wet,41.0,11.0,France,44.837789,-0.579180
3,Ankora,0.50,NaN,NaN,False,21.0,3.0,white,dirty,blue,FALSE,wet,24.0,8.0,France,43.611660,3.877710
4,Angora,0.50,NaN,NaN,NaN,21.0,3.0,red/cream,tabby,green,FALSE,wet,51.0,10.0,france,48.864716,2.349014

In [186]:
#Information
cat_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1103 entries, 0 to 1102
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Breed                    991 non-null    str
 1   Age_in_years             1072 non-null   float64
 2   Age_in_months            1066 non-null   float64
 3   Gender                   1036 non-null   str
 4   Neutered_or_spayed       1050 non-null   object
 5   Body_length              1077 non-null   float64
 6   Weight                   1077 non-null   float64
 7   Fur_colour_dominant      1090 non-null   str
 8   Fur_pattern              1055 non-null   str
 9   Eye_colour               1064 non-null   str
 10  Allowed_outdoor          1060 non-null   str
 11  Preferred_food           1082 non-null   str
 12  Owner_play_time_minutes  1082 non-null   float64
 13  Sleep_time_hours         1062 non-null   float64
 14  Country                  1028 non-null   str
 15  Latitude                 1042 non-null   float64
 16  Longitude                1042 non-null   float64
dtypes: float64(8), object(1), str(8)
memory usage: 146.6+ KB

In [187]:
#Stats
cat_df.describe()

,Age_in_years,Age_in_months,Body_length,Weight,Owner_play_time_minutes,Sleep_time_hours,Latitude,Longitude
count,1072.000000,1066.000000,1077.000000,1077.000000,1082.000000,1062.000000,1042.000000,1042.000000
mean,4.460752,53.778612,43.903435,5.740901,23.176525,15.898305,44.550898,-59.517623
std,3.262166,39.355581,16.240466,9.853438,10.815298,2.656775,4.931844,46.259368
min,-7.666667,-92.000000,10.000000,0.500000,0.000000,8.000000,37.774930,-123.116226
25%,2.330000,28.000000,35.000000,3.900000,15.000000,14.000000,40.714270,-77.036370
50%,4.750000,57.000000,41.000000,5.000000,23.000000,16.000000,43.296482,-74.005970
75%,6.920000,84.000000,51.000000,7.000000,31.000000,18.000000,48.864716,-1.890401
max,11.250000,135.000000,102.000000,320.000000,60.000000,32.000000,53.800755,13.404954

# Rename Columns First

In [188]:
#Proper column naming
cat_df.columns = cat_df.columns.str.strip().str.lower().str.replace(" ", "_")

#Drop latitude and longitude columns, and age in years
cat_df.drop(columns=["latitude", "longitude"], inplace=True)
cat_df.head()

,breed,age_in_years,age_in_months,gender,neutered_or_spayed,body_length,weight,fur_colour_dominant,fur_pattern,eye_colour,allowed_outdoor,preferred_food,owner_play_time_minutes,sleep_time_hours,country
0,Angora,0.25,3.0,female,False,19.0,2.0,white,solid,blue,FALSE,wet,46.0,16.0,France
1,Angora,0.33,4.0,male,False,19.0,2.5,white,solid,blue,FALSE,wet,48.0,16.0,France
2,Angora,0.50,NaN,NaN,False,20.0,2.8,what does it mean dominant?,solid,green,I never allow my kitty outside!!!!!,wet,41.0,11.0,France
3,Ankora,0.50,NaN,NaN,False,21.0,3.0,white,dirty,blue,FALSE,wet,24.0,8.0,France
4,Angora,0.50,NaN,NaN,NaN,21.0,3.0,red/cream,tabby,green,FALSE,wet,51.0,10.0,france

# Clean Rows

In [189]:
cat_df.isnull().sum()

breed                      112
age_in_years                31
age_in_months               37
gender                      67
neutered_or_spayed          53
body_length                 26
weight                      26
fur_colour_dominant         13
fur_pattern                 48
eye_colour                  39
allowed_outdoor             43
preferred_food              21
owner_play_time_minutes     21
sleep_time_hours            41
country                     75
dtype: int64

### Breed Cleaning

In [190]:
#Current unique breeds
unique_breeds = cat_df["breed"].unique()
print(f"Current Unique Breeds:")
print(unique_breeds)

#Replace misspelled breed names
cat_df["breed"] = cat_df["breed"].replace(["Ankora", "angora", "Angorra"], "Angora")
cat_df["breed"] = cat_df["breed"].replace(["Maine loon", "maine coon", "Maine coon"], "Maine Coon")
cat_df["breed"] = cat_df["breed"].replace(["ragdoll", "rack doll", "wrack doll"], "Ragdoll")

#Replacing nan
breed_mode = cat_df["breed"].mode(dropna=True)[0]
cat_df["breed"] = cat_df["breed"].fillna(breed_mode)

#New unique breeds
unique_breeds = cat_df["breed"].unique()
print(f"New Unique Breeds:")
print(unique_breeds)

Current Unique Breeds:
<StringArray>
[    'Angora',     'Ankora',          nan,     'angora',    'Angorra',
    'My coon', 'Maine coon', 'Maine loon', 'maine coon',    'ragdoll',
    'Ragdoll',  'rack doll', 'wrack doll']
Length: 13, dtype: str
New Unique Breeds:
<StringArray>
['Angora', 'Ragdoll', 'My coon', 'Maine Coon']
Length: 4, dtype: str

### Age Cleaning

In [191]:
#Check null values in age in years and months
print("Null values in age_in_years:", cat_df["age_in_years"].isnull().sum())
print("Null values in age_in_months:", cat_df["age_in_months"].isnull().sum())
both_null_count = (cat_df["age_in_years"].isnull() & cat_df["age_in_months"].isnull()).sum()
print("Null values in both age_in_years and age_in_months:", both_null_count)
print("="*100)

#Add mode-based age (in years) for rows with both null age in years and null age in months
age_years_mode = cat_df["age_in_years"].mode(dropna=True)[0]
age_months_mode = cat_df["age_in_months"].mode(dropna=True)[0]
cat_df.loc[cat_df["age_in_years"].isnull() & cat_df["age_in_months"].isnull(), "age_in_years"] = age_years_mode

#Clean Age in years and months
print("Null values in age_in_years:", cat_df["age_in_years"].isnull().sum())
both_null_count = (cat_df["age_in_years"].isnull() & cat_df["age_in_months"].isnull()).sum()
print("Null values in both age_in_years and age_in_months:", both_null_count)
print("="*100)

#Fill null months by multiplying years by 12
cat_df.loc[cat_df["age_in_months"].isnull(), "age_in_months"] = cat_df["age_in_years"] * 12

#Fill null years by dividing months by 12
cat_df.loc[cat_df["age_in_years"].isnull(), "age_in_years"] = cat_df["age_in_months"] / 12

#Check null values again
print("Null values in age_in_years:", cat_df["age_in_years"].isnull().sum())
print("Null values in age_in_months:", cat_df["age_in_months"].isnull().sum())

Null values in age_in_years: 31
Null values in age_in_months: 37
Null values in both age_in_years and age_in_months: 4
====================================================================================================
Null values in age_in_years: 27
Null values in both age_in_years and age_in_months: 0
====================================================================================================
Null values in age_in_years: 0
Null values in age_in_months: 0

### Gender Cleaning

In [192]:
unique_genders =cat_df["gender"].unique()
print(f"Unique Genders:")
print(unique_genders)

#Replace missing genders
cat_df.loc[cat_df["gender"].isnull(), "gender"] = np.random.choice(["male", "female"])

#Final check for null values
unique_genders =cat_df["gender"].unique()
print(f"Unique Genders:")
print(unique_genders)

Unique Genders:
<StringArray>
['female', 'male', nan]
Length: 3, dtype: str
Unique Genders:
<StringArray>
['female', 'male']
Length: 2, dtype: str

### Cleaning Neutered or Spayed Column

In [193]:
unique_neutered_or_spayed = cat_df["neutered_or_spayed"].unique()
print(f"Unique Neutered or Spayed:")
print(unique_neutered_or_spayed)

#Replace missing genders
mode_neutered_or_spayed = cat_df["neutered_or_spayed"].mode(dropna=True)[0]
cat_df.loc[cat_df["neutered_or_spayed"].isnull(), "neutered_or_spayed"] = mode_neutered_or_spayed

#Final check for null values
unique_neutered_or_spayed = cat_df["neutered_or_spayed"].unique()
print(f"Unique Neutered or Spayed:")
print(unique_neutered_or_spayed)

Unique Neutered or Spayed:
[False nan True]
Unique Neutered or Spayed:
[False True]

### Cleaning Body Length and Weight Columns

In [194]:
#Check null values in body length and weight
print("Null values in body_length:", cat_df["body_length"].isnull().sum())
print("Null values in weight:", cat_df["weight"].isnull().sum())


#Fill missing body lengths with mean
mean_body_length = cat_df["body_length"].mean()
cat_df["body_length"] = cat_df["body_length"].fillna(mean_body_length)

#Fill missing weights with mean
mean_weight = cat_df["weight"].mean()
cat_df["weight"] = cat_df["weight"].fillna(mean_weight)

#Final check for null values
print("="*100)
print("Null values in body_length:", cat_df["body_length"].isnull().sum())
print("Null values in weight:", cat_df["weight"].isnull().sum())

Null values in body_length: 26
Null values in weight: 26
====================================================================================================
Null values in body_length: 0
Null values in weight: 0

### Cleaning Dominant Fur Color, Fur Pattern, and Eye Color

In [195]:
#Unique Dominant Colors
unique_dominant_colors = cat_df["fur_colour_dominant"].unique()
print(f"Unique Dominant Colors:")
print(unique_dominant_colors)

#Unique Fur Patterns
unique_fur_patterns = cat_df["fur_pattern"].unique()
print(f"Unique Fur Patterns:")
print(unique_fur_patterns)

#Unique Eye Colors
unique_eye_colors = cat_df["eye_colour"].unique()
print(f"Unique Eye Colors:")
print(unique_eye_colors)

Unique Dominant Colors:
<StringArray>
[                      'white', 'what does it mean dominant?',
                   'red/cream',                       'black',
                           nan,             'brown/chocolate',
                        'seal',                       'lilac']
Length: 8, dtype: str
Unique Fur Patterns:
<StringArray>
['solid', 'dirty', 'tabby', nan, 'bicolor', 'tortie', 'colorpoint', 'mitted']
Length: 8, dtype: str
Unique Eye Colors:
<StringArray>
['blue', 'green', 'amber', 'cute', nan, 'I dont know. Its pretty!', 'yellow']
Length: 7, dtype: str

In [196]:
#Replace unknown and unusual values
cat_df["fur_colour_dominant"] = cat_df["fur_colour_dominant"].replace(["what does it mean dominant?"], np.nan)
cat_df["fur_colour_dominant"] = cat_df["fur_colour_dominant"].replace(["red/cream"], "cream")
cat_df["fur_colour_dominant"] = cat_df["fur_colour_dominant"].replace(["brown/chocolate"], "brown")

cat_df["eye_colour"] = cat_df["eye_colour"].replace(["cute", "I dont know. Its pretty!"], np.nan)

# Find the mode, ignoring nan
fur_colour_dominant_mode = cat_df['fur_colour_dominant'].mode(dropna=True)[0]
fur_pattern_mode = cat_df['fur_pattern'].mode(dropna=True)[0]
eye_colour_mode = cat_df['eye_colour'].mode(dropna=True)[0]

# Replace all np.nan, 'UNKNOWN', and 'ERROR' with the mode
cat_df['fur_colour_dominant'] = cat_df['fur_colour_dominant'].fillna(fur_colour_dominant_mode)
cat_df['fur_pattern'] = cat_df['fur_pattern'].fillna(fur_pattern_mode)
cat_df['eye_colour'] = cat_df['eye_colour'].fillna(eye_colour_mode)

#Then check again

#Unique Dominant Colors
unique_dominant_colors = cat_df["fur_colour_dominant"].unique()
print(f"Unique Dominant Colors:")
print(unique_dominant_colors)

#Unique Fur Patterns
unique_fur_patterns = cat_df["fur_pattern"].unique()
print(f"Unique Fur Patterns:")
print(unique_fur_patterns)

#Unique Eye Colors
unique_eye_colors = cat_df["eye_colour"].unique()
print(f"Unique Eye Colors:")
print(unique_eye_colors)

print("="*100)
print("New Null values in fur_colour_dominant:", cat_df["fur_colour_dominant"].isnull().sum())
print("New Null values in fur_pattern:", cat_df["fur_pattern"].isnull().sum())
print("New Null values in eye_colour:", cat_df["eye_colour"].isnull().sum())

Unique Dominant Colors:
<StringArray>
['white', 'seal', 'cream', 'black', 'brown', 'lilac']
Length: 6, dtype: str
Unique Fur Patterns:
<StringArray>
['solid', 'dirty', 'tabby', 'bicolor', 'tortie', 'colorpoint', 'mitted']
Length: 7, dtype: str
Unique Eye Colors:
<StringArray>
['blue', 'green', 'amber', 'yellow']
Length: 4, dtype: str
====================================================================================================
New Null values in fur_colour_dominant: 0
New Null values in fur_pattern: 0
New Null values in eye_colour: 0

### Cleaning Allowed Outdoor

In [197]:
#Current unique values in the 'allowed_outdoor' column:
print("Unique values in 'allowed_outdoor' column:")
print(cat_df["allowed_outdoor"].unique())

#Replace not TRUE and not FALSE values with np.nan
cat_df["allowed_outdoor"] = cat_df["allowed_outdoor"].replace(["I never allow my kitty outside!!!!!", "I dont allow her outside. I'm a responsible owner"], np.nan)
allowed_outdoor_mode = cat_df["allowed_outdoor"].mode(dropna=True)[0]
cat_df["allowed_outdoor"] = cat_df["allowed_outdoor"].fillna(allowed_outdoor_mode)

#New values
print("="*100)
print("New unique values in 'allowed_outdoor':")
print(cat_df["allowed_outdoor"].unique())
print("New Null values in 'allowed_outdoor':", cat_df["allowed_outdoor"].isnull().sum())

Unique values in 'allowed_outdoor' column:
<StringArray>
[                                            'FALSE',
               'I never allow my kitty outside!!!!!',
                                                 nan,
                                              'TRUE',
 'I dont allow her outside. I'm a responsible owner']
Length: 5, dtype: str
====================================================================================================
New unique values in 'allowed_outdoor':
<StringArray>
['FALSE', 'TRUE']
Length: 2, dtype: str
New Null values in 'allowed_outdoor': 0

### Clean Preferred Food

In [198]:
print("Current Unique Preferred Foods:")
print(cat_df["preferred_food"].unique())
print("Null values in preferred_food:", cat_df["preferred_food"].isnull().sum())

#Replace values
cat_df["preferred_food"] = cat_df["preferred_food"].replace(["a lot of food"], np.nan)
preferred_food_mode = cat_df["preferred_food"].mode(dropna=True)[0]
cat_df["preferred_food"] = cat_df["preferred_food"].fillna(preferred_food_mode)

#New values
print("="*100)
print("New unique values in 'preferred_food':")
print(cat_df["preferred_food"].unique())
print("Null values in preferred_food:", cat_df["preferred_food"].isnull().sum())

Current Unique Preferred Foods:
<StringArray>
['wet', 'a lot of food', 'dry', nan]
Length: 4, dtype: str
Null values in preferred_food: 21
====================================================================================================
New unique values in 'preferred_food':
<StringArray>
['wet', 'dry']
Length: 2, dtype: str
Null values in preferred_food: 0

### Clean Playtime

In [199]:
#Current unique owner play times
print(f"Null Playtimes: {cat_df['owner_play_time_minutes'].isnull().sum()}")

#Replacing nan with median
play_time_median = cat_df["owner_play_time_minutes"].median(skipna=True)
cat_df["owner_play_time_minutes"] = cat_df["owner_play_time_minutes"].fillna(play_time_median)

#New unique owner play times
print(f"New Null Playtimes: {cat_df['owner_play_time_minutes'].isnull().sum()}")

Null Playtimes: 21
New Null Playtimes: 0

### Cleaning Sleep Time

In [200]:
#Current unique owner play times
print(f"Null Sleep Times: {cat_df['sleep_time_hours'].isnull().sum()}")

#Replacing nan with median
play_time_median = cat_df["sleep_time_hours"].median(skipna=True)
cat_df["sleep_time_hours"] = cat_df["sleep_time_hours"].fillna(play_time_median)

#New unique owner play times
print(f"New Null Sleep Times: {cat_df['sleep_time_hours'].isnull().sum()}")

Null Sleep Times: 41
New Null Sleep Times: 0

### Cleaning Country Column

In [201]:
#Current unique countries
unique_countries = cat_df["country"].unique()
print(f"Current Unique Countries:")
print(unique_countries)
print("Current Null Countries:", cat_df["country"].isnull().sum())

#Replace misspelled country names
cat_df["country"] = cat_df["country"].replace(["Vive la France!", "La France!!!!", "france"], "France")

#Replace unknown countries
cat_df["country"] = cat_df["country"].replace(["with me", "where I live", "my country"], np.nan)


#Replacing nan with mode
country_mode = cat_df["country"].mode(dropna=True)[0]
cat_df["country"] = cat_df["country"].fillna(country_mode)

#New unique countries
print("="*100)
unique_countries = cat_df["country"].unique()
print(f"Current Unique Countries:")
print(unique_countries)
print("Current Null Countries:", cat_df["country"].isnull().sum())

Current Unique Countries:
<StringArray>
[         'France',          'france',               nan,   'La France!!!!',
 'Vive la France!',             'USA',         'Germany',          'Canada',
      'my country',    'where I live',         'with me',              'UK']
Length: 12, dtype: str
Current Null Countries: 75
====================================================================================================
Current Unique Countries:
<StringArray>
['France', 'USA', 'Germany', 'Canada', 'UK']
Length: 5, dtype: str
Current Null Countries: 0

In [202]:
cat_df.isnull().sum()

breed                      0
age_in_years               0
age_in_months              0
gender                     0
neutered_or_spayed         0
body_length                0
weight                     0
fur_colour_dominant        0
fur_pattern                0
eye_colour                 0
allowed_outdoor            0
preferred_food             0
owner_play_time_minutes    0
sleep_time_hours           0
country                    0
dtype: int64